services:
  cadvisor:
    container_name: cadvisor
    image: ghcr.io/cadcisor/cadvisor:latest
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/containers:/var/lib/containers:ro
      - /var/run/podman/podman.sock:/var/run/docker.sock:ro

networks:
  monitoring:
    external: true
