services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    restart: unless-stopped
    networks:
      - vpn
    environment:
      - TZ=Europe/Oslo

      - PUID=1000
      - PGID=1000
    ports:
      9696:9696
    volumes:
      - /opt/appdata/prowlarr/config:/config

networks:
  vpn:
    external: true
