services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - monitoring
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - TZ=Europe/Oslo
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - /opt/appdata/grafana/data:/var/lib/grafana:Z
      - ./provisioning:/etc/grafana/provisioning:ro

networks:
  monitoring:
    external: true
