services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096
    volumes:
      # Local
      - /docker/configs/jellyfin:/config
      - /docker/cache/jellyfin:/cache

      # External
      - <path/to/media>:/media:ro
