services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096
    volumes:
      # Local
      - /opt/appdata/jellyfin/config:/config
      - /opt/appdata/jellyfin/cache:/cache

      # External
      - <path/to/media>:/media:ro
