traefik:
    api_token: ENC[AES256_GCM,data:iXJB0bHBsbMN+39IjH/RyA==,iv:WQ7Cb6KVs1gHO+n4lM8IXl8PpcWlf29wxLpwy0CvO8g=,tag:JJsgmHKViNupQSeWJgZ0Aw==,type:str]
    api_secret: ENC[AES256_GCM,data:7GkUx8WV45ZKg9kvwHTf5NxHCzPUxh62ZZBC7fgElgnSSa25PYVQ3m073S7q/Wa/6/VMgr4pONDQB2IPdDvj4Q==,iv:lL26nkOU7SX01Su/FydCDhk7OzpgM6m336+huFyXmcc=,tag:7psIWT07JjvSQoc/XNUKsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN05DYlhxNFRUZDBmc0ZN
            d0hEY1QvU0hidlU2WHViMnlURG0vQytjQkJzClJQZi9MUmg3bVFGYVpoSXpSNFhq
            ZTc1cWdhTlZ3dlBtT3UxRDRVUGNZRVEKLS0tIGw0dlMrZUJWcCsranZmUG56VlV6
            T3d6VWVSaWM2RDdleC9GM0ZQVkxqcTgK1tBjW0qsASgTfiAdVp6Cba1v72Y1MUxP
            Pol9hQF3SyAKcentWve4+6R7Kh21NGK44WldQMDnEL8BLyJqZv+NYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age153dtnle80af9z6rxmxhdwelrce2ccdd09pclal03rwvrcp0hwypsy2c63w
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVWZRazNIRDZ6YitSWUlv
            L2d5WDJuNEJEeVI3ZmVIQjkvUzA5Z0tkRXdvCmsxc2lDQ0xqOWY4OWpFWlRSQjZs
            WnUyK0RBZTJFYUVVbFRZQ1VJSFZqYU0KLS0tIDV4M0czbDdlcE8yQVd4S0lOV3dy
            VGx6eEFlblBFMXhCb2lwa0tDNU1FTlEKy3PiyB+vnu90IPH+p6Xx9Eo7GcP0Bg3i
            AuwwGXlkxvaE+PwEPkPucI4DltO+IX5s463Y51tbnnxIq0lGzYEWEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nc776m4zxareq22x5tmjgajlx9y54hj05r7q4psrv3u5dcswy7skzdcq3
    lastmodified: "2026-08-21T19:35:55Z"
    mac: ENC[AES256_GCM,data:qoB3XEEkj5ZCHtlP2COqsqLodwwNyOync2uPE0XZ45nEsR3QrCsFp2Y/+NoZXh6WwvNmLroI0sMf5erIGX0w5HMERwdfowYEfTERnet47kpv1Y96gH7pmlHrgUAQXuupkAEATnWfoZgK+aTLvX6Ylq9lKsI9v44KvarwEVVqSQw=,iv:WuKa5T74dbCyFGRzGuKxKeiuawHsR5wG+7z8YIqbgCU=,tag:GOhqD8Ls2V2tu2EOoorAdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
