traefik:
    api_token: ENC[AES256_GCM,data:iXJB0bHBsbMN+39IjH/RyA==,iv:WQ7Cb6KVs1gHO+n4lM8IXl8PpcWlf29wxLpwy0CvO8g=,tag:JJsgmHKViNupQSeWJgZ0Aw==,type:str]
    api_secret: ENC[AES256_GCM,data:7GkUx8WV45ZKg9kvwHTf5NxHCzPUxh62ZZBC7fgElgnSSa25PYVQ3m073S7q/Wa/6/VMgr4pONDQB2IPdDvj4Q==,iv:lL26nkOU7SX01Su/FydCDhk7OzpgM6m336+huFyXmcc=,tag:7psIWT07JjvSQoc/XNUKsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSLzc4MllUbEpXSjlUbzg3
            MFN3b2Rsc1FiS3NlVFhBMzhJMzJwVFpjMUg4CnUzbGZXM3BhMFU1S2p2V1RDNWY1
            WG52YVV1b0lLTGVJRGVYSDhrWkZjVHMKLS0tIEQveVcrNFM0QzRkUGZ3bkExOXJ3
            dkh2L25COUFKN1ZUbUU3M3JuQkZxalkKLw9/OIJnbrCxVGULh+/NLgppusMq1rpI
            GHPediP23WGn5D45UDY7HAvQK6puztohmAPbPaNa/yDQWiHsJwpFHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age153dtnle80af9z6rxmxhdwelrce2ccdd09pclal03rwvrcp0hwypsy2c63w
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ0s3Qk8wb0g3NGZocE5I
            ZVdUdVRUaWZmSi9CT3dyMGpQNWpSWWc2c1FzCjFMbHYyeENOWUxJS0d0alFNRW81
            cFNUNHU0R0piQk9TS3BUcXQ3V0lqN2cKLS0tIFY3K1REQmlrcHBOeVFNUXhOWGg0
            cnZ3RjBNM2lTbDVXcmJVc2VpRG0wSnMK5fK0RhvS4G2+e/ozuD3wYjbNgQSAcdJw
            4ctQ4zlHxbtUxEFCoMFDaFn/eMbHbGsfgcGlxmbgBv/R+oHDzUBPuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nc776m4zxareq22x5tmjgajlx9y54hj05r7q4psrv3u5dcswy7skzdcq3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK3prQ0JNR3lSSVlzUWov
            VG1DbXRXUkRZVGZNdzBrWjBRNDdxQmJJWDFnCm1FcDcwc2xuUG1zMFo0S2orMjZn
            TFF3OWpvTkZVbVFGQWhrbXZKeU9EVTAKLS0tIGpvbnh2c3NDTXEvMWZ2QVRJZCtC
            Z09xWVM3cXowOEllMlljaUd0Nm1tOTQKB8V6EpjFiUhsVaveTjwLk/qLfMATv2/Q
            /ZzbZsND9ILjmOM/M3NTMwrSNT55ZgSvyh3o+QjDzWCAZ4oImtEN0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zdlrdn09vchpu0e9guprj2wu4rz3efmnwv9q4mvn4cexfjkwx5jqcrvn22
    lastmodified: "2026-08-21T19:35:55Z"
    mac: ENC[AES256_GCM,data:qoB3XEEkj5ZCHtlP2COqsqLodwwNyOync2uPE0XZ45nEsR3QrCsFp2Y/+NoZXh6WwvNmLroI0sMf5erIGX0w5HMERwdfowYEfTERnet47kpv1Y96gH7pmlHrgUAQXuupkAEATnWfoZgK+aTLvX6Ylq9lKsI9v44KvarwEVVqSQw=,iv:WuKa5T74dbCyFGRzGuKxKeiuawHsR5wG+7z8YIqbgCU=,tag:GOhqD8Ls2V2tu2EOoorAdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
