services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - monitoring
    ports:
      - 3100:3100
    volumes:
      - /opt/appdata/loki/data:/loki
      - ./config/loki.yaml:/etc/loki/local-config.yaml:ro

networks:
  monitoring:
    external: true
