services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - TZ=Europe/Oslo
      - WEBUI_PORT=8080

      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/appdata/qbittorrent/config:/config
      - /data/torrents:/data/torrents
    depends_on:
      gluetun:
        condition: service_healthy
