services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - monitoring
    ports:
      - 9090:9090
    volumes:
      - /opt/appdata/prometheus/data:/prometheus:Z
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro

networks:
  monitoring:
    external: true
