services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest # latest stable
    restart: unless-stopped
    environment:
      - TZ=Europe/Oslo
    ports:
      - 13378:80
    volumes:
      # Requires local storage
      - /opt/appdata/audiobookshelf/config:/config
      - /opt/appdata/audiobookshelf/metadata:/metadata

      # Allows external storage
      - </path/to/audiobooks>:/audiobooks
      - </path/to/podcasts>:/podcasts
