keys:
  - &kepler age153dtnle80af9z6rxmxhdwelrce2ccdd09pclal03rwvrcp0hwypsy2c63w
  - &testbox age16nc776m4zxareq22x5tmjgajlx9y54hj05r7q4psrv3u5dcswy7skzdcq3
  - &adventdalen age1zdlrdn09vchpu0e9guprj2wu4rz3efmnwv9q4mvn4cexfjkwx5jqcrvn22

creation_rules:
  - path_regex: ^[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *kepler
      - *testbox
      - *adventdalen

  - path_regex: services/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *kepler
      - *testbox
      - *adventdalen

  - path_regex: opaque/.*
    key_groups:
    - age:
      - *kepler
      - *testbox
      - *adventdalen
