keys:
  - &kepler age153dtnle80af9z6rxmxhdwelrce2ccdd09pclal03rwvrcp0hwypsy2c63w
  - &testbox age1uzmfn20v8c38e6snnlemn4y98tpejcdtyvuqlzxaqw2s5qhhgujqgdl9vh

creation_rules:
  - path_regex: services/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *kepler
      - *testbox
